version: "2"

linters:
  default: none
  enable:
    - errcheck    # Errcheck is a program for checking for unchecked errors in Go code.
    - govet       # Vet examines Go source code and reports suspicious constructs.
    - ineffassign # Detects when assignments to existing variables are not used.
    - importas    # Enforces consistent import aliases.
    - staticcheck # It's the set of rules from staticcheck.
    - unused      # Checks Go code for unused constants, variables, functions and types.
    - bodyclose   # hecks whether HTTP response body is closed successfully.
    - revive      # Fast, configurable, extensible, flexible, and beautiful linter for Go.
    - gosec       # Inspects source code for security problems.

  exclusions:
    generated: lax
    warn-unused: false
    rules:
      - path: api/docs/
        linters:
          - revive

      - path: internal/repository/
        linters:
          - staticcheck
          - errcheck
          - revive

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true

run:
  timeout: 5m
  modules-download-mode: readonly
