services:
  api:
    build:
      target: prod
    image: vanish-vault-api:${TAG}
    env_file:
      - .env.prod
    restart: always
    environment:
    - GIN_MODE=${GIN_MODE:-release}

  db:
    restart: always

  redis:
    restart: always

  caddy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
