services:
  api:
    build:
      context: .
      target: prod
    image: vanish-vault-api:${TAG}
    restart: always
    secrets:
      - pg_password
    environment:
    - GIN_MODE=release

  db:
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password

  caddy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

secrets:
  pg_password:
    file: ./secrets/pg_password.txt