services:
  api:
    build:
      target: dev
    image: vanish-vault-api:${TAG}
    env_file:
      - .env
    volumes:
      - ./:/app:cached
      - /app/tmp
    environment:
      - GIN_MODE=${GIN_MODE:-debug}

  db:
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  caddy:
    ports:
      - "80:80"
      - "443:443"
