// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProviderType string

const (
	AuthProviderTypeGoogle AuthProviderType = "google"
	AuthProviderTypeGithub AuthProviderType = "github"
)

func (e *AuthProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProviderType(s)
	case string:
		*e = AuthProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProviderType: %T", src)
	}
	return nil
}

type NullAuthProviderType struct {
	AuthProviderType AuthProviderType `json:"auth_provider_type"`
	Valid            bool             `json:"valid"` // Valid is true if AuthProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProviderType), nil
}

type MemberRoleType string

const (
	MemberRoleTypeAdmin  MemberRoleType = "admin"
	MemberRoleTypeEditor MemberRoleType = "editor"
	MemberRoleTypeViewer MemberRoleType = "viewer"
)

func (e *MemberRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRoleType(s)
	case string:
		*e = MemberRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRoleType: %T", src)
	}
	return nil
}

type NullMemberRoleType struct {
	MemberRoleType MemberRoleType `json:"member_role_type"`
	Valid          bool           `json:"valid"` // Valid is true if MemberRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRoleType), nil
}

type RoomMember struct {
	RoomID    uuid.UUID          `json:"room_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      MemberRoleType     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SecretItem struct {
	ID               uuid.UUID          `json:"id"`
	RoomID           uuid.UUID          `json:"room_id"`
	CreatorID        uuid.UUID          `json:"creator_id"`
	EncryptedContent []byte             `json:"encrypted_content"`
	Nonce            []byte             `json:"nonce"`
	IsBurned         pgtype.Bool        `json:"is_burned"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BurnedAt         pgtype.Timestamptz `json:"burned_at"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	Provider   AuthProviderType   `json:"provider"`
	ProviderID string             `json:"provider_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type VaultRoom struct {
	ID         uuid.UUID          `json:"id"`
	OwnerID    uuid.UUID          `json:"owner_id"`
	Name       string             `json:"name"`
	AccessCode pgtype.Text        `json:"access_code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
