// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMemberToRoom(ctx context.Context, arg AddMemberToRoomParams) (RoomMember, error)
	BurnSecret(ctx context.Context, id uuid.UUID) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (VaultRoom, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (SecretItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRoom(ctx context.Context, arg DeleteRoomParams) error
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (MemberRoleType, error)
	GetSecretForView(ctx context.Context, arg GetSecretForViewParams) (SecretItem, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	ListMyRooms(ctx context.Context, userID uuid.UUID) ([]VaultRoom, error)
	ListSecretsByRoom(ctx context.Context, roomID uuid.UUID) ([]ListSecretsByRoomRow, error)
}

var _ Querier = (*Queries)(nil)
