// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProviderType string

const (
	AuthProviderTypeGoogle AuthProviderType = "google"
	AuthProviderTypeGithub AuthProviderType = "github"
)

func (e *AuthProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProviderType(s)
	case string:
		*e = AuthProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProviderType: %T", src)
	}
	return nil
}

type NullAuthProviderType struct {
	AuthProviderType AuthProviderType
	Valid            bool // Valid is true if AuthProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProviderType), nil
}

type MemberRoleType string

const (
	MemberRoleTypeAdmin  MemberRoleType = "admin"
	MemberRoleTypeEditor MemberRoleType = "editor"
	MemberRoleTypeViewer MemberRoleType = "viewer"
)

func (e *MemberRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRoleType(s)
	case string:
		*e = MemberRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRoleType: %T", src)
	}
	return nil
}

type NullMemberRoleType struct {
	MemberRoleType MemberRoleType
	Valid          bool // Valid is true if MemberRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRoleType), nil
}

type RoomMember struct {
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	Role      MemberRoleType
	CreatedAt pgtype.Timestamptz
}

type SecretItem struct {
	ID               pgtype.UUID
	RoomID           pgtype.UUID
	CreatorID        pgtype.UUID
	EncryptedContent []byte
	Nonce            []byte
	IsBurned         pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	BurnedAt         pgtype.Timestamptz
}

type User struct {
	ID         pgtype.UUID
	Email      string
	Provider   AuthProviderType
	ProviderID string
	CreatedAt  pgtype.Timestamptz
}

type VaultRoom struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	AccessCode pgtype.Text
	ExpiresAt  pgtype.Timestamptz
	IsActive   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
}
